project:
  type: website
  output-dir: docs

website:
  title: ""
  
  navbar:
    search: false
    logo: images/logo.png 
    background: transparent
    right:
      - text: "Home"
        href: index.qmd
      - text: "News"
        href: news.qmd
      - text: "Team"
        href: team.qmd
      - text: "Research"
        href: research.qmd
      - text: "Approach"
        href: approach.qmd
      - text: "Publication"
        href: publication.qmd
      - text: "Apps"
        href: shinyapp.qmd
      - text: "Join us!"
        href: position.qmd
      - contact.qmd
      - text: ""
        href: "https://x.com/chenchong446337"
        icon: twitter


format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
    header-includes: |
      <!-- Google tag (gtag.js) -->
      <script async src="https://www.googletagmanager.com/gtag/js?id=G-LPGSNSC5VK"></script>
      <script>
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      
      gtag('config', 'G-LPGSNSC5VK');
      </script>
      
      <link rel="icon" href="images/favicon.png" type="image/x-icon" sizes="any">
      
      <style>
      
      .navbar-brand img {
          height: 70px !important; /* Adjust height as needed */
          width: auto !important;  /* Maintain aspect ratio */
          max-height: none !important; /* Remove max-height constraints */
          max-width: none !important; /* Remove max-width constraints */
        }
        
        /* Footer styling */
        footer {
          text-align: center;
          padding: 10px 0;
          background-color: #f8f9fa;
          color: #6c757d;
          font-size: 14px;
          border-top: 1px solid #e9ecef;
          position: fixed;
          bottom: 0;
          width: 100%;
        }
        
        /* Style for the text box */
        .text-box {
          max-width: 600px; /* Restrict the width of the text box */
          margin: -20 auto;   /* Center the box */
          padding: 0px;    /* Add some padding inside the box */
          text-align: justify; /* Optional: Align text to the left */
          background-color: transparant; /* Optional: Background color */
          border-radius: 8px; /* Optional: Add rounded corners */
        }
      </style>

editor: visual
