project:
  type: website

website:
  title: ""
  
  navbar:
    search: false
    logo: images/logo.png 
    background: primary
    left:
      - text: "Home"
        href: index.qmd
      - talks.qmd
      - team.qmd
      - contact.qmd
      - about.qmd 

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

editor: visual

