---
title: ""
toc: false
---

<footer style="background-color: transparent; text-align: left; padding: 10px 0; color: black; font-size: 14px; border-top: 1px solid rgba(0, 0, 0, 0.1);">

Chen Lab \| Westlake © 2024 Hangzhou, Zhejiang Province, China

</footer>

## We are recruiting!

We are seeking graduate students and postdocs to study the neurobiology of pain, opioids, and anesthesia. First-year Ph.D. students at Westlake University are welcome to select our lab for rotations. Visiting scholars who can commit to staying in the lab for more than two years are also encouraged to apply. Positions for visiting students and research assistants are limited, but qualified candidates planning to pursue [Ph.D. training](https://www.westlake.edu.cn/admissions_aid/graduate/) in our lab are strongly encouraged to apply.

Our lab is situated in a vibrant, interdisciplinary, and collaborative research environment at [Westlake University](https://www.westlake.edu.cn/), with opportunities for international collaborations to broaden research perspectives. Our lab operates under the principle of **"Work smarter, not harder"**. If you are interested in applying, please [email](mailto:chenchong@westlake.edu.cn) me with a description of your research experience and interests, along with your CV and contact information for references.
