---
title: ""
toc: false
---

<style>
  footer {
    position: fixed;
    bottom: -50px;
    left: 0;
    width: 100%; /* Ensure the footer spans the entire page */
    background-color: black;
    text-align: left;
    padding: 10px 0;
    color: white;
    font-size: 14px;
    border-top: 1px solid rgba(0, 0, 0, 0.1);
    transition: transform 0.5s ease-in-out;
  }

  body {
    margin: 0; /* Remove any default margin that might interfere */
  }

  footer.show {
    transform: translateY(-50px); /* Bring footer into view */
  }
</style>
<script>
  document.addEventListener("scroll", function () {
    const footer = document.querySelector("footer");
    const scrollHeight = document.documentElement.scrollHeight;
    const scrollPosition = window.innerHeight + window.scrollY;

    // Check if the user has scrolled to the bottom
    if (scrollPosition >= scrollHeight) {
      footer.classList.add("show");
    } else {
      footer.classList.remove("show");
    }
  });
</script>

<footer>Chen Lab \| Westlake © 2024 Hangzhou, Zhejiang Province, China</footer>

## Citation Network Explorer

The Citation Network Explorer is a user-friendly web application designed to help researchers and academics explore the citation network of one or multiple papers with ease. By simply entering the PMID of the paper(s) of interest, users can visualize and analyze the connections between citing and cited articles. This app offers valuable insights into the academic influence and connectivity of research papers in a specific field.

::: {style="text-align: center;"}
<iframe src="https://chenchong446337.shinyapps.io/citation_network1/" 
          width="110%" 
          height="600px" 
          style="border: 1px solid #ccc;"> Your browser does not support iframes. Please visit the app directly: <a href="https://chenchong446337.shinyapps.io/citation_network1/">Shiny App</a>. </iframe>
:::

## Gene Co-expression Network Explorer

The Gene Co-Expression Network Explorer is an intuitive tool designed to help researchers investigate co-expression relationships between genes in a given dataset. Using the single cell RNA-Seq dataset from the *Kebschull et al., 2020* paper, this app allows users to input a specific gene name and explore its co-expression network, identifying genes that are co-upregulated or co-downregulated. The app also features community detection and Gene Ontology (GO) analysis, enabling a deeper understanding of functional relationships between co-expressed genes.

::: {style="text-align: center;"}
<iframe src="https://chenchong446337.shinyapps.io/gene_network/" 
          width="110%" 
          height="600px" 
          style="border: 1px solid #ccc;"> Your browser does not support iframes. Please visit the app directly: <a href="https://chenchong446337.shinyapps.io/gene_network/">Shiny App</a>. </iframe>
:::
